### ISSUE TITLE
bad interpreter

### ISSUE THREAD

**Issue by Hans-Maulwurf** [twostairs/snoo#1]
I only get an exception like "bad interpreter"
> bash: /usr/bin/snoo: node: Defekter Interpreter: Datei oder Verzeichnis nicht gefunden

What to do?

**Comment by mrusme** [comment]
@Hans-Maulwurf install node >= 7.4.0. :-)

**Comment by Hans-Maulwurf** [comment]
> node -v
> v7.5.0

that's my output :/

**Comment by mrusme** [comment]
@Hans-Maulwurf just [updated something](https://github.com/twostairs/snoo/commit/1f1b4e128c884232a2184b8900077d8d22790382). Could you please `git pull` / `npm i` the latest version and try again?

**Comment by Hans-Maulwurf** [comment]
now i get
> /usr/bin/env: „node --harmony“: Datei oder Verzeichnis nicht gefunden

**Comment by mrusme** [comment]
Could you run the following command in your terminal?

```bash
$ /usr/bin/env node --version
v7.5.0
```

**Comment by Hans-Maulwurf** [comment]
> v7.5.0
using arch linux

**Comment by Hans-Maulwurf** [comment]
I got it working now. It seems it's the way you call node, I changed the first line of cli.js to

> #!/usr/bin/node --harmony

and now it's working :)

**Comment by mrusme** [comment]
From what I know `#!/usr/bin/env node` is the suggested way, as the node binary doesn't necessarily need to be under `/usr/bin/`. So for users that installed node into e.g. `/opt`, your solution would not work as well.

I'm really wondering how come that when you run `/usr/bin/env node` manually it works, but when your shell interprets the shebang statement it apparently can't find it anymore. That's really weird.
